### ISSUE TITLE
calendarview request failing when too much data returned in 1.5.2

### ISSUE THREAD

**Issue by edlea** [microsoftgraph/msgraph-sdk-javascript#158] opened 2019-04-06 14:18 UTC
Making requests for a calendarview that returns more than a few events seems to cause a silent failure; i.e. the Promise from get() never resolves or rejects.

This is not the case with version 1.4.0 but happens repeatably with 1.5.2. By changing the date range in the below code example, this is fully reproducible. A short time gap, a single day for example, returns data as expected. For a longer time period, the code will simply stop executing before get() has resolved or rejected.

```
const microsoftGraph = require("@microsoft/microsoft-graph-client");
const token = process.env.TOKEN;
const client = microsoftGraph.Client.init({
    debugLogging: true,
    authProvider: (done) => {
        done(null, token);
    }
});

const startdatetime = "2018-01-01T00:00:00Z";
const enddatetime = "2018-01-31T00:00:00Z"; // Fails when big delta from startdatatime
const req = client.api(`me/calendar/calendarview?StartDateTime=${startdatetime}&EndDateTime=${enddatetime}`);
req.get().then(console.log).catch(console.error);
```

**Comment by Ricardonacif** [comment] 2019-04-08 21:29
Yup, I faced the same issue on 1.5.2. Had to go back to 1.4.0

**Comment by muthurathinam** [comment] 2019-04-10 08:12
@edlea @Ricardonacif I am not able to reproduce the issue with your sample code in node v11.11.0. Please help me with the following,
* what is your node version ?
* I understand that by big delta you mean the response from server, and this response is restricted with a default page size of 10. Are you using top() [odata query param] to get more events ?

**Comment by edlea** [comment] 2019-04-10 08:35
This is occurring in node 8.10 on AWS Lambda. No other arguments beyond the example code are being used

**Comment by muthurathinam** [comment] 2019-04-25 09:03
Can you try this preview build and let me know whether you face the same error with preview build also.
https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/1.6.0-Preview.3
install preview build by `npm i @microsoft/microsoft-graph-client@Preview`

**Comment by edlea** [comment] 2019-04-25 14:44
That doesn't seem to have made a difference

**Comment by borys-kupar** [comment] 2019-05-10 08:44
I can confirm that the same issue happened to me too when result contains more than 30 events with a select of "start,end,body" fields. The body contain small piece of HTML that has several <p> tags basically. This didn't seem to happen with 1.4 version.

**Comment by muthurathinam** [comment] 2019-06-25 04:57
This issue is fixed in [2.0.0-Preview.1](https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0-Preview.1). @edlea @borys-kupar @Ricardonacif Can you try and check whether it fixes for you ?

**Comment by jlphelps** [comment] 2019-06-27 21:33
I was experiencing this issue and can confirm that [2.0.0-Preview.1](https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0-Preview.1) fixes it for me.

**Comment by muthurathinam** [comment] 2019-08-27 08:46
Published stable release for the same
https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0

**Closed by muthurathinam** 2019-08-27 08:46 UTC
Labels: fixed
