### ISSUE TITLE
`rawResponse.blob is not a function` when get `/users/${id}/photo/$value`

### ISSUE THREAD

**Issue by wy193777** [microsoftgraph/msgraph-sdk-javascript#262] opened 2019-12-24 20:42 UTC
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Got a TypeError when using 
```
const profilePhoto = await graphClient
    .api(`/users/${id}/photo/$value`)
    .get();
```

**Console Errors:** [Is there any console error]
{"statusCode":200,"code":"TypeError","message":"rawResponse.blob is not a function","requestId":null,"date":"2019-12-24T20:37:04.824Z","body":"TypeError: rawResponse.blob is not a function","level":"error","timestamp":"2019-12-24T20:37:04.825Z"}

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

Using `client_id` and `client_secret` to get credential. 
Make a request to get photo.

**Expected behavior:** Get the photo.

**Actual behavior:** Got error

## Additional Context

Add any other context about the problem here..

## Usage Information

SDK Version - [SDK version you are using]

-   [x] Node (Check, if using Node version of SDK)

> Node Version - [v12.14.0]

**Comment by peombwa** [comment] 2020-02-20 22:50
Duplicate of #210. Use `.getStream()` instead.

**Closed by peombwa** 2020-02-20 22:50 UTC
Labels: ToTriage
