### ISSUE TITLE
StreamUpload is not a constructor

### ISSUE THREAD

**Issue by ApsaraPrabodani** [microsoftgraph/msgraph-sdk-javascript#471] opened 2021-06-14 06:52 UTC
## Description

Im using the node express.js for our project and we are using `msgraph-sdk-javascript` for connecting with Microsoft graph APIs.

for the record we use following line to get sdk to our app and then created client object.

const graph = require('@microsoft/microsoft-graph-client');

const fileObject = new graph.StreamUpload(stream, fileMeta.document_name, fileMeta.file_size);

but unfortunately when we are trying to use LargeFileUploadTask to upload a file with size of more than 4Mb, It saying 
'StreamUpload is not a constructor'

Any other way to get StreamUpload, LargeFileUploadTask functions without directly importing it.

<img width="1272" alt="Screenshot 2021-06-14 at 12 18 16" src="https://user-images.githubusercontent.com/22188258/121850908-17a5ac80-cd0b-11eb-9d98-23d3d1e05c5a.png">

> SDK Version - 2.2.1
> Node Version - v14.5.0

Thanks.
 
[AB#9884](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9884)

**Comment by nikithauc** [comment] 2021-06-14 17:36
@ApsaraPrabodani Thanks for  reaching out! 

The StreamUpload feature will be introduced in the 3.0.0 version. 

The preview for this version is out. Can you try installing the version 3.0.0-Preview.2? 
- https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/3.0.0-Preview.2
- `npm i @microsoft/microsoft-graph-client@3.0.0-Preview.2`

**Comment by ApsaraPrabodani** [comment] 2021-06-15 08:00
@nikithauc thank you soo much for the quick response.

As you mentioned earlier, installed version 3.0.0-Preview.2 And
then can get access to StreamUpload and LargeFileUploadTask functions with new version.

But agin showing this error with upload task.

<img width="1275" alt="Screenshot 2021-06-15 at 13 27 15" src="https://user-images.githubusercontent.com/22188258/122015491-c61a2200-cddd-11eb-9107-8c7be57e8112.png">

**Comment by nikithauc** [comment] 2021-06-15 08:19
@ApsaraPrabodani 

Can you please provide the code that your are using?

What is the upload session URL that you are using? 

Can you please provide more information about the API that you are trying to upload to and any details that can help me reproduce this issue?

**Comment by ApsaraPrabodani** [comment] 2021-06-15 08:33
@nikithauc ,
Thank you again for the quick response, Im trying to upload a large file to Microsoft site.

This is the url for creating upload session,
`const url = `/sites/${data.site_id}/drives/${data.drive_id}/root:/${data.document_name}:/createUploadSession`;`

and then creating upload session from this,
```
const graph = require('@microsoft/microsoft-graph-client');
require('isomorphic-fetch');

       const url = /sites/${data.site_id}/drives/${data.drive_id}/root:/${data.document_name}:/createUploadSession;
       const payload = {
                item: {
                    '@microsoft.graph.conflictBehavior': 'rename',
                    name: fileMeta.document_name,
                },
         };

         const uploadSession = graph.LargeFileUploadTask.createUploadSession(
                this.client,
                url, 
                payload
          );

         const fileObject = new graph.StreamUpload(stream, fileMeta.document_name, fileMeta.file_size);
         const uploadTask = new graph.LargeFileUploadTask(this.client, fileObject, uploadSession);
         const uploadResult = await uploadTask.upload();
```

If you need any more information, please get back to me.
thanks.

**Comment by nikithauc** [comment] 2021-06-15 08:46
@ApsaraPrabodani  Thanks for providing the details!

Can you please verify if the upload session is being created and is the URL property of the upload session being set?

**Comment by ApsaraPrabodani** [comment] 2021-06-15 08:55
@nikithauc ,
It is creating upload session with given url.

<img width="1268" alt="Screenshot 2021-06-15 at 14 22 26" src="https://user-images.githubusercontent.com/22188258/122023732-6de71e00-cde5-11eb-85a9-85b30247d127.png">

**Comment by ApsaraPrabodani** [comment] 2021-06-15 13:25
@nikithauc ,

After some workarounds , managed to execute the upload function in uploadTask. But still having a issue with upload function.

`const uploadResult = await uploadTask.upload();`

above method is hanging forever I guess. not returning any error or noting. just hanging there

<img width="528" alt="Screenshot 2021-06-15 at 18 51 34" src="https://user-images.githubusercontent.com/22188258/122059931-bfee6a80-ce0a-11eb-992e-41ddadc45217.png">


and upload session url gives following response as well as,
<img width="855" alt="Screenshot 2021-06-15 at 18 52 32" src="https://user-images.githubusercontent.com/22188258/122060222-03e16f80-ce0b-11eb-9e33-14b8d586f540.png">

Did I do anything wrong? why is code not giving any response even errors)

thanks.

**Comment by nikithauc** [comment] 2021-06-15 20:18
@ApsaraPrabodani 

Can you please tell me what was causing the `index of undefined error`?

The upload function can take a while if the file size is large. 

What is the size of your file? 
Are you not getting any response after the complete file is uploaded?

The file is sliced into multiple parts and each part is uploaded sequentially. You can set a `UploadEventHandler.Progress` callback and verify the range that is being uploaded successfully. 

```
const progress = (range?: Range, extraCallBackParam?: unknown) => {
	// Handle progress event
};

const uploadEventHandlers: UploadEventHandlers = {
	progress,
	extraCallBackParam, // additional parameters to the callback
};

const options: LargeFileUploadTaskOptions = {
	rangeSize: 327680,
	uploadEventHandlers: UploadEventHandlers,
};

```

https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/tasks/LargeFileUploadTask.md

**Comment by ApsaraPrabodani** [comment] 2021-06-16 04:37
@nikithauc ,

Earlier I didn't await for creating upload session function. As I think that could be problem of `index of undefined error`.
After await that function, it works fine.

Im trying to upload 4.3MB file. The thing is, once waited around 2 hours for any response.

and of course used progress function and added only console.logs for checking status.

```
          const progress = (range, extraCallBackParam) => {
                console.log('uploading range: ', range);
                return true;
            };
            
            const uploadEventHandlers = {
                progress
            };
            
            const options = {
                rangeSize: 1024*1024,
                uploadEventHandlers,
            };

            const uploadTask = new graph.LargeFileUploadTask(this.client, fileObject, uploadSession, options);
```
This the result of progress function,

<img width="528" alt="Screenshot 2021-06-15 at 18 51 34" src="https://user-images.githubusercontent.com/22188258/122157000-b820db80-ce87-11eb-95cd-d8388bcebd7d.png">

And other thing is , its creating temp file in Sharepoint site, but not completing,
<img width="654" alt="Screenshot 2021-06-16 at 09 49 09" src="https://user-images.githubusercontent.com/22188258/122158568-878e7100-ce8a-11eb-846f-037da29b7757.png">

thanks.

**Comment by nikithauc** [comment] 2021-06-17 07:54
@ApsaraPrabodani 

Following is the code that I am trying and it worked. I was able to get the result. 

Can you please try if this code works for you? 

```
async function  upload(){
    const pay =  {
        "item": {
            "@microsoft.graph.conflictBehavior": "rename"
        }
    }

    const progress = (range, extraCallBackParam) => {
        console.log('uploading range: ', range);
        return true;
    };
    
    const uploadEventHandlers = {
        progress
    };
    
    const options = {
        rangeSize: 1024*1024,
        uploadEventHandlers,
    };
const uploadSession = await new MicrosoftGraph.LargeFileUploadTask.createUploadSession(client,"https://graph.microsoft.com/v1.0/sites/root/drive/items/{item-id}/createuploadsession", pay);
const file = fs.createReadStream('./test.pdf');


const stats = fs.statSync(`./test.pdf`);
	const totalsize = stats.size;

const stream = new MicrosoftGraph.StreamUpload(file,'test.pdf',totalsize);
const task = new MicrosoftGraph.LargeFileUploadTask(client,stream,uploadSession,options);
const uploadResult = await task.upload();
console.log(uploadResult); 
}
/*




```

**Comment by nikithauc** [comment] 2021-06-21 04:37
@ApsaraPrabodani  did the large file upload process work for you ?

**Comment by nikithauc** [comment] 2021-06-30 05:54
Closing this due to inactivity.

@ApsaraPrabodani  Please feel free to open a new issue or comment here in case you have any questions

**Closed by nikithauc** 2021-06-30 05:54 UTC
Labels: not actionable
