### ISSUE TITLE
Error TS2307: Cannot find module '@microsoft/microsoft-graph-client'

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-javascript#61] opened 2018-01-23 17:49 UTC
https://stackoverflow.com/questions/48380812/error-ts2307-cannot-find-module-microsoft-microsoft-graph-client

Error TS2307: Cannot find module '@microsoft/microsoft-graph-client'.
The same happens, when trying to import @microsoft/microsoft-graph-types. Oddly, VS Code resolves the path to the module correctly, but gulp throws the above mentioned error while building.

2123487

**Comment by lumayara** [comment] 2018-03-27 16:47
I am getting the same error.

**Comment by MIchaelMainer** [comment] 2018-03-27 17:47
@lumayara I'm sorry that I haven't gotten to this.

**Comment by sibelius** [comment] 2018-09-12 12:51
this is fixed, can we close?

**Comment by sibelius** [comment] 2018-09-12 21:56
related to this https://github.com/microsoftgraph/msgraph-typescript-typings/issues/24

**Comment by muthurathinam** [comment] 2019-02-12 04:19
@lumayara I cannot reproduce this error are you still getting this ? If so can you please provide me the steps to reproduce ?
FYI: I am using the latest version of the microsoft/microsoft-graph-client.

**Comment by muthurathinam** [comment] 2019-02-13 03:45
User reported this is fixed. Hence closing.!

**Closed by muthurathinam** 2019-02-13 03:45 UTC
Labels: needs more info, tracked

**Comment by rogercodes1** [comment] 2020-01-23 00:14
Still seeing this error on 1.7.0 and 2.0.0
What information do you need from me?
