### ISSUE TITLE
Ho do i get recurring event instances in the /me/calendarView endpoint?

### ISSUE THREAD

**Issue by markg85** [microsoftgraph/msgraph-sdk-javascript#187] opened 2019-06-08 11:38 UTC
Hi,

I'm trying to get the all my calendar events as they are visible in the office 365 calendar. For that, i'm using the [calendarView](https://docs.microsoft.com/en-us/graph/api/calendar-list-calendarview?view=graph-rest-1.0&tabs=cs). It returns me just the events that don't have a recurrence.

But i have a recurrence in there that is visible in outlook, but not in the results of this api call.

Now `/me/events` does return recurring series, just not individual ones, and i can query each event with `/me/events/ID/instances` which does (eventually) give me the data i expect, but that's a whole lot more complicated and much more API calls then just calling `/me/calendarView`. Is this the intended case of how it should be used or is this a bug of the calendarView endpoint?

**Comment by shaundon** [comment] 2019-06-10 07:23
I would also like to know this.

**Comment by shaundon** [comment] 2019-06-10 07:30
I figured it out, this works for me:

```
client
  .api(`/me/calendar/calendarView?startDateTime=<date_here>&endDateTime=<date_here>`)
  .get()
;

```

**Comment by markg85** [comment] 2019-06-10 09:55
> I figured it out, this works for me:
> 
> ```
> client
>   .api(`/me/calendar/calendarView?startDateTime=<date_here>&endDateTime=<date_here>`)
>   .get()
> ;
> ```

That's exactly what i did (with valid dates) and it certainly didn't show events of recurring events.

That sounds weird, so let me explain that a little more. Make a recurring event, say every monday, then use that API call to get the events within a date range that should contain at least 1 of those events, but not the very first or last one of the series.

**Comment by shaundon** [comment] 2019-06-10 10:26
Strange, that's exactly what I'm doing and it's fine for me 😕

**Comment by markg85** [comment] 2019-06-10 10:42
> Strange, that's exactly what I'm doing and it's fine for me

Are you absolutely sure you're testing the same thing?
I have a weekly occurring event on monday and a bi-weekly ones on friday. Neither shows.
They are all in the same agenda, i just re-verified that.

My API call:
```
let from = moment().toISOString()
let till = moment().add(1, 'month').toISOString()

const data = await client.api(`/me/calendar/calendarView?startDateTime=${from}&endDateTime=${till}`)
.select(['categories', 'start', 'end', 'subject'])
.get();
```

**Comment by muthurathinam** [comment] 2019-06-11 05:15
Duplicate of https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/155

**Closed by muthurathinam** 2019-06-11 05:15 UTC
