### ISSUE TITLE
Event creation timeZone is intermittently ignored

### ISSUE THREAD

**Issue by technicallynick** [microsoftgraph/msgraph-sdk-javascript#269] opened 2020-03-03 02:27 UTC
# Bug Report

## Prerequisites

-   [Y] Can you reproduce the problem?
-   [Y] Are you running the latest version?
-   [Y] Are you reporting to the correct repository?
-   [Y] Did you perform a cursory search?

## Description
When creating a new event via `/me/events` endpoint, the start.timeZone and end.timeZone are both **_intermittently_** ignored. The timezone being supplied is in the list of timezones from `/me/outlook/supportedTimeZones` but 60-80% of the time, the timezone returned is UTC while the time is unchanged.

For instance, if I supply the following: 

```
{
subject: "arg",
body: {contentType: "HTML", content: "arg"},
start: {dateTime: "2020-03-03T03:00:00", timeZone: "Pacific Standard Time"},
end: {dateTime: "2020-03-03T04:00:00", timeZone: "Pacific Standard Time"},
attendees: []
}
```
The (truncated) results will show: 

```
{
originalStartTimeZone: "UTC",
originalEndTimeZone: "UTC",
start: { dateTime: "2020-03-03T03:00:00.0000000", timeZone: "UTC"},
end: { dateTime: "2020-03-03T04:00:00.0000000", timeZone: "UTC"}
}
```

**Console Errors:** 
No errors returned.

## Steps to Reproduce

1. Create event object and specify non-UTC timezone listed in your `supportedTimeZones`
2. Use MSGraph API to submit this event.
3. Witness Response contains (sometimes) UTC timezone instead of the specified timezone.

When using `fetch()`, issue does not occur.

**Expected behavior:** 
I expect that a specified timezone will be honored. If the timezone is invalid, then an error should be returned specifying why.

**Actual behavior:** 
Timezone is erroneously changed to UTC without regard to the time values.

## Usage Information

SDK Version - 2.0

-   [Y] Node (Check, if using Node version of SDK)

> Node Version - v10.19.0

**Comment by Tony357** [comment] 2020-03-04 04:34
We are having the same issue but via me/findMeetingTimes/ endpoint.

**Request**
{
  "timeConstraint": {
    "timeSlots": [
      {
        "start": {
          "dateTime": "2020-03-05T11:00:00",
          "timeZone": "Tokyo Standard Time"
        },
        "end": {
          "dateTime": "2020-03-05T12:00:00",
          "timeZone": "Tokyo Standard Time"
        }
      }
    ],
    "activityDomain": 3
  }
}

**Response**
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#microsoft.graph.meetingTimeSuggestionsResult",
    "emptySuggestionsReason": "",
    "meetingTimeSuggestions": [
        {
            "confidence": 100,
            "organizerAvailability": "free",
            "attendeeAvailability": [],
            "locations": [],
            "meetingTimeSlot": {
                "start": {
                    "dateTime": "2020-03-05T11:00:00.0000000",
                    "timeZone": "UTC"
                },
                "end": {
                    "dateTime": "2020-03-05T11:30:00.0000000",
                    "timeZone": "UTC"
                }
            }
        },
        {
            "confidence": 100,
            "organizerAvailability": "free",
            "attendeeAvailability": [],
            "locations": [],
            "meetingTimeSlot": {
                "start": {
                    "dateTime": "2020-03-05T11:30:00.0000000",
                    "timeZone": "UTC"
                },
                "end": {
                    "dateTime": "2020-03-05T12:00:00.0000000",
                    "timeZone": "UTC"
                }
            }
        }
    ]
}

**Comment by tomngo** [comment] 2020-03-04 06:47
We found this bug as well. We have evidence that was working fine on 2020-03-02 at 19:55:00 UTC, and we first detected the incorrect behavior on 2020-03-03 at around 23:15:00 UTC.

Request contains: 
`"start": {"dateTime": "2020-03-04T08:00:00.000000", "timeZone": "America/New_York"}, "end": {"dateTime": "2020-03-04T08:30:00.000000", "timeZone": "America/New_York"}`

Response contains:
`"start": {"dateTime": "2020-03-04T08:00:00.0000000", "timeZone": "UTC"}, "end": {"dateTime": "2020-03-04T08:30:00.0000000", "timeZone": "UTC"}`

**Comment by tomngo** [comment] 2020-03-04 13:26
**Frequency**: Response incorrectly contained UTC in 11/11 tests between 
2020-03-03 at around 23:15:00 UTC and
2020-03-04 at around 03:45:00 UTC

Prior to that time, the response was correct 100% of the time (as far as we know), in production, for six months at least.

Just now (2020-03-04 at around 10:25:00 UTC), the response was correct.

**Comment by aspartame** [comment] 2020-03-04 19:31
We experienced this issue too, in the REST API with creating calendar events with `POST` to `/v1.0/users/{Resource}/events`.

Requests were in UTC-08 (America/Los_Angeles) but responses had the timezone for both `start`/`end` and `originalStartTimeZone`/`originalEndTimezone` set to UTC.

We first discovered this at around 23:00 UTC on 2020-03-03.
Still reproducible at 02:30 UTC on 2020-03-04.
No longer reproducible as of now (19:30 UTC on 2020-03-04).

**Comment by tomngo** [comment] 2020-03-04 19:35
Confirming @aspartame 's experience: we've tested a couple dozen times between
2020-03-04 at around 10:25:00 UTC and
2020-03-04 at around 19:30:00 UTC (now)
with no problems.

@MSFT: Was this a regression that got fixed, or a server running old code, or something else?

**Comment by MIchaelMainer** [comment] 2020-03-05 21:15
We on the client library team are learning about this now. I'm not aware of any regressions that cause this. Since this appears to have been fixed we are closing this issue. 

@kaevne

**Closed by MIchaelMainer** 2020-03-05 21:15 UTC
Labels: bug: service

**Comment by tomngo** [comment] 2020-03-06 19:40
I think we have just proved that this issue is intermittent: two people independently reported that it happened, and the client library team isn't aware of any cause.

What's the right way to ensure that an intermittent problem gets solved?

**Comment by MIchaelMainer** [comment] 2020-03-09 21:04
@tomngo This is an area that we have much opportunity to improve upon. There isn't an adequate way for customers to open and track issues against the service APIs. We can do it here in the client repos, but it will likely not get the acknowledgment that you'd like to see.

**Comment by tomngo** [comment] 2020-03-10 03:29
@MIchaelMainer Thank you so much for the follow-up. I'm comfortable with not having a way to open and track an issue, and not having a way to request acknowledgment.

However, I would advocate keeping this issue open. This issue is appears to be intermittent. Since nobody knows why the bad behavior went away, it seems that 2020-03-04 19:30:00 UTC was merely the end of one incident, not evidence of a permanent fix.
