### ISSUE TITLE
Property 'LargeFileUploadTask' does not exist  /node_modules/@microsoft/microsoft-graph-types/microsoft-graph"

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/msgraph-sdk-javascript#456] opened 2021-05-19 12:49 UTC
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Using 
`import * as MicrosoftGraph from '@microsoft/microsoft-graph-types';`
The line:
`const uploadSession = MicrosoftGraph.LargeFileUploadTask.createUploadSession(client, "REQUEST_URL", payload);`

Based on the documentation [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-Mgq8WKoEvw2fMogMT2Z8IQ&epi=je6NUbpObpQ-Mgq8WKoEvw2fMogMT2Z8IQ&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=%28ir__9jittyihmkkftyvtx6ahfkwm9u2xumul99g06w9u00%29%287593%29%281243925%29%28je6NUbpObpQ-Mgq8WKoEvw2fMogMT2Z8IQ%29%28%29&irclickid=_9jittyihmkkftyvtx6ahfkwm9u2xumul99g06w9u00)

Has TSlint complain "Property 'LargeFileUploadTask' does not exist on type 'typeof import("{mypath}/node_modules/@microsoft/microsoft-graph-types/microsoft-graph")'.ts(2339)"

Am Using the right code?

SDK Version - [1.12.1]

-   [] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]

-   [X] Browser (Check, if using Browser version of SDK)

 
[AB#9511](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9511)

**Comment by nikithauc** [comment] 2021-05-19 20:30
@Ofer-Gal can you try installing npm version 2.1.1 - https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/2.2.1 ?

**Comment by Ofer-Gal** [comment] 2021-05-19 22:09
Yes
`import * as MicrosoftGraph from '@microsoft/microsoft-graph-client';` works
Not `'@microsoft/microsoft-graph-types'`
Thank you.
Maybe you have an example of complete Large file upload to SharePoint library?
All I can find are bits and pieces that do not make sense.

**Comment by nikithauc** [comment] 2021-05-20 07:45
@Ofer-Gal 
`@microsoft/microsoft-graph-types`  contains only objects representing entities of the Microsoft Graph API. The `largefileupload` tasks and the middleware to make requests to the Graph API are present in `@microsoft/microsoft-graph-client`.

Can you try if the following would code work for you? 

```
    const requestUrl = "https://graph.microsoft.com/v1.0/sites/{siteId}/drive/items/{itemId}/createUploadSession";

    const fileName = "<YOUR_FILE>";
    const file = fs.readFileSync(`./${fileName}`);
    const stats = fs.statSync(`./${fileName}`);

    const payload = {
        "@microsoft.graph.conflictBehavior": "rename",
        "description": "description",
        "fileSize": stats.size,
        "name": file
    }
    const uploadSession = await MicrosoftGraph.LargeFileUploadTask.createUploadSession(client, requestUrl, payload);

    const fileObject = {
        content: file,
        name: fileName,
        size: stats.size
    };

    const task = new MicrosoftGraph.LargeFileUploadTask(client, fileObject, uploadSession);

    const response = task.upload();

```

Please let me know if you have more questions.

**Comment by Ofer-Gal** [comment] 2021-05-20 11:48
Thanks. that is good only I have 2 questions:

1. If the file I am uploading is new to the library. I do I know what {itemId} to add to the first line in your code? any other option?
2. What is fs.??? in line 2 and 3? can I use File type instead? (I have a FileList to work with) 

Thank you much

**Comment by nikithauc** [comment] 2021-05-20 21:11
@Ofer-Gal 
Please find more information on `item` and `itemid` here.

https://docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http
https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0

**Comment by Ofer-Gal** [comment] 2021-05-20 21:38
Will love to tell you.
I am working on a SPFx web part that users will use to submit files to different sites libraries (based on project number). the current part uses pnp/js "AddChunck" method but we found out that up to 10% of the times we get "Fail to Fetch" error. So I want to try the all mighty graph that everyone says it is the way to go. Up to now, the "Client" created from SPFx was not compatible with the one in the graph JS SDK. with 2.2.1 it is now compatible but all the examples I found so far did not work or did not explain what to do right.

As for the "itemid" I am guessing it means the root (or folder) in the library (drive in graph speak. (why change terms? more confusion?)) I did not find any documentation saying it is the folder.
So far your answer was the best I got so far. 
Thank you much. I will try it out and let you know.

**Comment by Ofer-Gal** [comment] 2021-05-22 18:27
@nikithauc,   Finally found the trick no-one else but Ryan Gregg showed in [stackoverflow.com](https://stackoverflow.com/questions/40369180/microsoft-graph-uploading-files-to-shared-library-instead-of-users-library)
graph may be good but the documentation sucks very much.
Thank you for your help.

**Comment by nikithauc** [comment] 2021-05-25 19:56
Hi @Ofer-Gal, 

It was nice talking to you. 
The progress tracking of the upload is a feature that will be released in 3.0.0. 

You can check out this feature in preview of 3.0.0 - https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/3.0.0-Preview.1.
`npm i @microsoft/microsoft-graph-client@3.0.0-Preview.1`

Following is an example on how to track the progress of the upload using 3.0.0 version -

imports 
```
import { FileUpload, LargeFileUploadTaskOptions, UploadEventHandlers, UploadResult, LargeFileUploadTask  } from "@microsoft/microsoft-graph-client";
```

```
const extraCallBackParams = 'EXTRA_PARAMS FOR_ CALLBACK' // Set this to any extra custom parameters to access in the progress callback.
```

**Set your progress callback**
- Parameters to the callback 
// range: [Range](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/master/src/Range.ts) is the range of bytes uploaded successfully 
// extraCallBackParams - any extra custom parameters to access in the progress call back.
```
const yourProgressCallBack = (range?: Range, extraCallBackParams?: unknown) => {
 //  your progress tracking callback goes here
		};
```

Set the `yourProgressCallBack ` and `extraCallbackParam` in `UploadEventHandlers`
```
const uploadEventHandlers: UploadEventHandlers = {
	yourProgressCallBack ,
	extraCallbackParam: ,
};
```

Set  uploadEventHandlers in `LargeFileUploadTaskOptions`
```
const largeFileUploadTaskOptions: LargeFileUploadTaskOptions= {
	uploadEventHandlers: ,
};
```

```
const requestUrl = "https://graph.microsoft.com/v1.0/sites/{siteId}/drive/items/{itemId}/createUploadSession";

const fileName = "<YOUR_FILE>";
const file = fs.readFileSync(`./${fileName}`);
const stats = fs.statSync(`./${fileName}`);

// Example payload
const payload = {
      "@microsoft.graph.conflictBehavior": "rename",
      "description": "description",
      "fileSize": stats.size,
      "name": fileName 
  }
const uploadSession = await MicrosoftGraph.LargeFileUploadTask.createUploadSession(client, requestUrl, payload);

const fileObject = new FileUpload(file, fileName , stats.size); 

//  **pass `largeFileUploadTaskOptions` here**  
  const task = new MicrosoftGraph.LargeFileUploadTask(client, fileObject, uploadSession, largeFileUploadTaskOptions); 

  const response: UploadResult = await  task.upload();
```

* You can also use [StreamUpload](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/src/tasks/FileUploadTask/FileObjectClasses/StreamUpload.ts) object or have a custom implementation of the [FileObject](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/ed06eb73cf8ed819ca2b9938cb077416e3e25334/src/tasks/LargeFileUploadTask.ts#L75) interface with the `sliceFile` logic function. 
* https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/tasks/LargeFileUploadTask.md

**Comment by Ofer-Gal** [comment] 2021-05-25 22:11
@nikithauc Thank you!
I installed the 3.0.0 and changed the code as you will see below. But I get an error from inside your code.
`TypeError: Cannot read property 'get' of undefined
    at Function.<anonymous> (GraphResponseHandler.js:94)
    at Generator.next (<anonymous>)
    at tslib.es6.js:76
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:72)
    at Function.convertResponse (GraphResponseHandler.js:88)
    at Function.<anonymous> (GraphResponseHandler.js:168)
    at Generator.next (<anonymous>)
    at tslib.es6.js:76
    at new Promise (<anonymous>)`
TypeScript only accepted : LargeFileUploadTask<T> as type but I did not know what the T should be. is it File | blob | Stream ?
Here is the code: the error is on the last line.
```
//------------------------Begin Large File Upload with Graph------------------------------------
const uploadEventHandlers: UploadEventHandlers = {progress: yourProgressCallBack };
const largeFileUploadTaskOptions: LargeFileUploadTaskOptions = {
    uploadEventHandlers: uploadEventHandlers,
    rangeSize: 320 * 1024
};
const requestUrl = `https://graph.microsoft.com/v1.0/sites/${graphIds.siteID}/drives/${graphIds.DriveID}/root:/${fixFileName}:/createUploadSession`;
const fContent = await file.downloadFileContent();
const payload = {
    "@microsoft.graph.conflictBehavior": "replace", "description": "What for? ", "fileSize": file.fileSize, "name": fixFileName
};
const uploadSession = await MicrosoftGraph.LargeFileUploadTask.createUploadSession(graphIds.client, requestUrl, payload);
const fileObject = new FileUpload(fContent, fixFileName, file.fileSize);
const uploadTask= new MicrosoftGraph.LargeFileUploadTask(graphIds.client, fileObject, uploadSession, largeFileUploadTaskOptions);
const uploadResult: UploadResult = await uploadTask.upload();
//------------------------end Large File Upload with Graph------------------------------------

```
Hope you can help figure it out

**Comment by nikithauc** [comment] 2021-05-25 22:27
@Ofer-Gal 

What is the type of `fContent` ? 
 `FileUpload`  is for content of format - `ArrayBuffer | Blob | Buffer`.

Can you try the following?
`const fileObject = new FileUpload(Buffer.from(fContent), fixFileName, file.fileSize)`;

`T` represents the use of generics here. 
In case of `FileUpload` `T` binds to `ArrayBuffer | Blob | Buffer`.
In case of `StreamUpload` `T` binds to `Readable` that is the Node.js  `Readable Stream`.

**Comment by Ofer-Gal** [comment] 2021-05-25 23:19
the type of fContent id type  downloadFileContent: () => Promise<File>;
It has a method .arrayBuffer() but TypeScript says:"TS2339: Property 'arrayBuffer' does not exist on type 'File'." So I made the type any.
Only uploadTask: LargeFileUploadTask<Blob | ArrayBuffer | Buffer>  is OK by Typescript. :-(
So I made it any too.
But I still get the same error:
```
GraphResponseHandler.js:94 Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at Function.<anonymous> (GraphResponseHandler.js:94)
    at Generator.next (<anonymous>)
    at tslib.es6.js:76
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:72)
    at Function.convertResponse (GraphResponseHandler.js:88)
    at Function.<anonymous> (GraphResponseHandler.js:168)
    at Generator.next (<anonymous>)
    at tslib.es6.js:76
    at new Promise (<anonymous>)
```
Now the code is:
```
//------------------------Begin Large File Upload with Graph------------------------------------
const uploadEventHandlers: UploadEventHandlers = {
    progress: yourProgressCallBack 
};
const largeFileUploadTaskOptions: LargeFileUploadTaskOptions = {
    uploadEventHandlers: uploadEventHandlers,
    rangeSize: 320 * 1024
};
const requestUrl = `https://graph.microsoft.com/v1.0/sites/${graphIds.siteID}/drives/${graphIds.DriveID}/root:/${fixFileName}:/createUploadSession`;
let theContent = await file.downloadFileContent();
const fContent: ArrayBuffer = await theContent.arrayBuffer(); //This is an arrayBuffer
const payload = {
    "@microsoft.graph.conflictBehavior": "replace", "description": "What for? ", "fileSize": file.fileSize, "name": fixFileName
};
const uploadSession = await MicrosoftGraph.LargeFileUploadTask.createUploadSession(graphIds.client, requestUrl, payload);
const fileObject = new FileUpload(fContent, fixFileName, file.fileSize);
const uploadTask = new MicrosoftGraph.LargeFileUploadTask(graphIds.client, fileObject, uploadSession, largeFileUploadTaskOptions);
const uploadResult: UploadResult = await uploadTask.upload();
debugger;
console.log(uploadResult);
//------------------------end Large File Upload with Graph------------------------------------
```
thank you

**Comment by nikithauc** [comment] 2021-05-26 00:30
@Ofer-Gal  

I tried passing a `File`  object to create a `FileUpload` object and it works fine. 

 What is the return type of `await file.downloadFileContent()`?

If `await file.downloadFileContent()` returns `File` type. You can directly use 
```
const fileContent:File = await file.downloadFileContent();

const fileObject = new FileUpload(fContent, fixFileName, file.fileSize);

```
I tried the following and I did not get any compile time error - 

```
const file = new File(["ssssssssssss"], name);
const fileObj = new FileUpload(file, name, size);
```

The  following error indicates that the GraphResponseHandler is not getting a response when trying to upload the chunk, that is, the response is `undefined`.
`
Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at Function.<anonymous> (GraphResponseHandler.js:94)
`

Can you trace the request and response during each chunk upload?

**Comment by Ofer-Gal** [comment] 2021-05-26 12:37
Using ```let fContent: File  = await file.downloadFileContent(); ``` was OK for the tslinter did not help.
Using the test ```fContent = new File(["ssssssssssssOfer"], fixFileName);``` couse bunch of other errors even before the upload.
with the selected file, when getting to line 94 in GraphResponseHandler, Only rawResponse.headers is undefined
rawResponse is:
```
{@odata.context: "https://ecgmcdev.sharepoint.com/teams/T001.016/_api/v2.0/$metadata#items/$entity", @content.downloadUrl: "https://ecgmcdev.sharepoint.com/teams/T001.016/_la…1NjQlBPR0lzRllMTlR2a3Rpb2txTXNIYz0&ApiVersion=2.0", createdBy: {…}, createdDateTime: "2021-05-25T22:54:08Z", eTag: "\"{9DA60DFB-6952-463D-B643-5336A8E08975},6\"", …}
@content.downloadUrl: "https://ecgmcdev.sharepoint.com/teams/T001.016/_layouts/15/download.aspx?UniqueId=9da60dfb-6952-463d-b643-5336a8e08975&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvZWNnbWNkZXYuc2hhcmVwb2ludC5jb21AZWMwOWZjYzQtMmUxYS00YmZhLWI4ZmMtNGEwYTFkYmE2NGZlIiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTYyMjAzMTI5NiIsImV4cCI6IjE2MjIwMzQ4OTYiLCJlbmRwb2ludHVybCI6ImlHZi90L0dFTy80SDBKMzRaUFBteEtSY3Rab2VOc2xFa3BvQlpOV0FXVnM9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIxMzQiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6Ik5qTmhZMk5pT1dZdE5EQmpNaTB3TURBd0xXUTFOR1F0TldZM1l6Um1NVGt3T0RsayIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJZakE0WVdaallqZ3RZelExWXkwME5UTTFMV0V6TmpFdFl6RmpaR1UyTmpSbVpqWmsiLCJhcHBfZGlzcGxheW5hbWUiOiJTaGFyZVBvaW50IE9ubGluZSBDbGllbnQgRXh0ZW5zaWJpbGl0eSBXZWIgQXBwbGljYXRpb24gUHJpbmNpcGFsIiwiZ2l2ZW5fbmFtZSI6Ik9mZXIiLCJmYW1pbHlfbmFtZSI6IkdhbCIsInNpZ25pbl9zdGF0ZSI6IltcImttc2lcIl0iLCJhcHBpZCI6IjA0YzQ0NTY1LWE4OGYtNGM1MC1hZDEyLTFmYTJkZmY3MGIyOSIsInRpZCI6ImVjMDlmY2M0LTJlMWEtNGJmYS1iOGZjLTRhMGExZGJhNjRmZSIsInVwbiI6Im9mZXJAZWNnbWNkZXYub25taWNyb3NvZnQuY29tIiwicHVpZCI6IjEwMDMyMDAwNjAwMkY2QTAiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwxMDAzMjAwMDYwMDJmNmEwQGxpdmUuY29tIiwic2NwIjoibXlmaWxlcy53cml0ZSBhbGxmaWxlcy53cml0ZSBhbGxzaXRlcy5yZWFkIGFsbHNpdGVzLndyaXRlIGFsbHByb2ZpbGVzLnJlYWQgYWxscHJvZmlsZXMucmVhZCBhbGxwcm9maWxlcy53cml0ZSIsInR0IjoiMiIsInVzZVBlcnNpc3RlbnRDb29raWUiOiIzIn0.bHk0SS9zZS9lS3drL2d3RHNpQ1NjQlBPR0lzRllMTlR2a3Rpb2txTXNIYz0&ApiVersion=2.0"
@odata.context: "https://ecgmcdev.sharepoint.com/teams/T001.016/_api/v2.0/$metadata#items/$entity"
cTag: "\"c:{9DA60DFB-6952-463D-B643-5336A8E08975},8\""
createdBy: {application: {…}, user: {…}}
createdDateTime: "2021-05-25T22:54:08Z"
eTag: "\"{9DA60DFB-6952-463D-B643-5336A8E08975},6\""
file: {hashes: {…}, irmEnabled: false, mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"}
fileSystemInfo: {createdDateTime: "2021-05-25T22:54:08Z", lastModifiedDateTime: "2021-05-26T12:14:57Z"}
id: "01YEEMXHH3BWTJ2UTJHVDLMQ2TG2UOBCLV"
lastModifiedBy: {application: {…}, user: {…}}
lastModifiedDateTime: "2021-05-26T12:14:57Z"
name: "DPC Work Request.docx"
parentReference: {driveId: "b!uPyKsFzENUWjYcHN5mT_bWK7D27N88dEkPx657C2OvE1lv8ipp9bTJbncll5KqH0", driveType: "documentLibrary", id: "01YEEMXHF6Y2GOVW7725BZO354PWSELRRZ", path: "/drives/b!uPyKsFzENUWjYcHN5mT_bWK7D27N88dEkPx657C2OvE1lv8ipp9bTJbncll5KqH0/root:"}
size: 51354
webUrl: "https://ecgmcdev.sharepoint.com/teams/T001.016/_layouts/15/Doc.aspx?sourcedoc=%7B9DA60DFB-6952-463D-B643-5336A8E08975%7D&file=DPC%20Work%20Request.docx&action=default&mobileredirect=true"
[[Prototype]]: Object
```
Can I just attach a header to it?

**Comment by nikithauc** [comment] 2021-06-01 17:09
@Ofer-Gal  I am working on a sample to use the large file upload task from the 3.0.0-preview version. 

`fContent = new File(["ssssssssssss"], fixFileName)` this is an just an example I used to reproduce the `T` error that you reported.

Are you still getting the same error with the headers?

**Comment by Ofer-Gal** [comment] 2021-06-01 21:25
I reverted to 2.2.1 and gave up on the progress report.
I think there is some disconnect between the 3.0.0-preview version and the graph factory of SPFx.
My work is a SharePoint framework web part and I can't use 3.0.0 as is.

**Comment by nikithauc** [comment] 2021-06-07 21:30
@Ofer-Gal  

I learned that SPFx uses the Graph client 1.x version. The 3.x changes may not be compatible with 1.x Graph client. 

Are you using a version 1.x Graph client?

References- 
https://www.sebastienlevert.com/2021/04/18/latest-microsoft-graph-client-spfx/

**Comment by Ofer-Gal** [comment] 2021-06-07 22:05
I do something similar to connect 2.2.1 but it did not help 3.0.0 preview

**Closed** 2021-06-24 18:30 UTC
Labels: question

**Comment by rdick** [comment] 2021-09-09 17:59
Hello @nikithauc,

I am trying to upload a file (> 4 MB) directly from React to SharePoint with the Microsoft Graph API. Here is my code below.

I keep getting the following error:
**Please provide the Readable Stream content, name of the file and size of the file**

**new FileUpload
/src/tasks/FileUploadTask/FileObjectClasses/FileUpload.ts:28**

I think it is because I am uploading a file (instead of a readable stream) to - new FileUpload(file,name,size). Can I turn a file to a readable stream in React?

Could you assist with this? If this not possible is the only other way from an API on the backend? How would I transfer my access code to the backend?

``

` 
// Function 1 - GET UPLOADED FILE FROM USER IN REACT

    const fileUpload = (e,b) => {

        const file1 = e.target.files[0]
        console.log('instance of file', file1 instanceof File) // TRUE
        uploadLargeDocument(app.authProvider, fileObj)
}

// Function 2 - UPLOAD FILE TO SHAREPOINT

 export async function uploadLargeDocument(authProvider, file) {
      ensureClient(authProvider);

      const it_site_id = 'xyz'

      const requestUrl = `https://graph.microsoft.com/v1.0/sites/${it_site_id}/drive/items/root:/Code/doggy5:/createUploadSession`
        
      const payload = {
          "@microsoft.graph.conflictBehavior": "replace",
          "description": "description",
          "fileSize": file.size,
          "name": file.name
      }
      const uploadSession = await LargeFileUploadTask.createUploadSession(graphClient, requestUrl, payload);

     // ERROR - Please provide the Readable Stream content, name of the file and size of the file
      const fileObject = new FileUpload({
          content: file,
          name: file.name,
          size: file.size
      })

      const task = new LargeFileUploadTask(graphClient, fileObject, uploadSession);
      
      const response = task.upload();

      return response
  }`
