### ISSUE TITLE
Incorrect Content-Type in put() call. Default Content-Type should be application/json

### ISSUE THREAD

**Issue by vdnsv** [microsoftgraph/msgraph-sdk-javascript#183] opened 2019-06-05 16:15 UTC
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Method put() creates options object with Content-Type: application/octet-stream in headers instead of application/json:

	public async put(content: any, callback?: GraphRequestCallback): Promise<any> {
		const url = this.buildFullUrl();
		const options: FetchOptions = {
			method: RequestMethod.PUT,
			body: serializeContent(content),
			headers: {
				"Content-Type": "application/octet-stream",
			},
		};
		try {
			const response = await this.send(url, options, callback);
			return response;
		} catch (error) {
			throw error;
		}
	}

**Console Errors:**

GraphError {
  statusCode: 400,
  code: 'UnknownError',
  message: 'Argument: sourceEntity, Value:  is null.',
  requestId: '7c662662-70f8-4226-96d7-190cbefd4590',
  date: 2019-06-05T13:04:12.000Z,
  body:
   '{"code":"UnknownError","message":"Argument: sourceEntity, Value:  is null.","innerError":{"request-id":"7c662662-70f8-4226-96d7-190cbefd4590","date":"2019-06-05T16:04:12"}}' }

## Steps to Reproduce

await client.api(`/teams/${teamId}/schedule/schedulingGroups/${schedulingGroupId}`)
            .version('beta')
            .put(schedulingGroup)

**Expected behavior:**
It should work.

**Actual behavior:**
Exception with Status Code 400 and strange message "Argument: sourceEntity, Value:  is null."

**Comment by muthurathinam** [comment] 2019-06-07 07:05
@vdnsv I understand your concern, this was left out not to break the current flow. Will change this in our v2.0 release and make application/json as a default content-type.
Meanwhile use this work around,
```js
await client.api(/teams/${teamId}/schedule/schedulingGroups/${schedulingGroupId})
                   .version('beta')
                   .header("Content-Type", "application/json")
                   .put(schedulingGroup)
```

**Comment by muthurathinam** [comment] 2019-06-25 05:10
Fix for the issue is released with Preview tag. @vdnsv Check it out https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0-Preview.1

**Comment by muthurathinam** [comment] 2019-08-27 08:46
Published stable release for the same
https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0

**Closed by muthurathinam** 2019-08-27 08:46 UTC
Labels: fixed
