### ISSUE TITLE
First time access of a file shared from a user's OneDrive throws generic error

### ISSUE THREAD

**Issue by FreshlyBrewedCode** [microsoftgraph/msgraph-sdk-javascript#490] opened 2021-08-02 12:59 UTC
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [ ] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

## Description

I am trying to fetch the `downloadUrl` of a file shared from a user's OneDrive using the share URL ([see docs](https://docs.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http))
```
GET /shares/{encodedSharingUrl}/driveItem
```

The code I am using looks like this:
```typescript
client.api(`/shares/${encodedUrl}/driveItem`)
  .get()
  .then((result) => {
      if (result.error) {
          console.error(
              "Error fetching sharepoint src: " +
                  result.error
          );
      } else {
          setDonwloadUrl(
              result["@microsoft.graph.downloadUrl"]
          );
      }
  })
  .catch((e) => {
      console.error(e);
  })
```
This works without problems in most cases. However, if user A shares a file from his OneDrive (using the option "People in *\<Organization\>* with the link") and user B tries to access the file the promise is rejected with a generic error:
```
Error
    at Function.<anonymous> (http://localhost:3000/static/js/vendors~main.chunk.js:53294:18)
    at Generator.next (<anonymous>)
    at http://localhost:3000/static/js/vendors~main.chunk.js:59284:67
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:3000/static/js/vendors~main.chunk.js:59263:10)
    at Function.getError (http://localhost:3000/static/js/vendors~main.chunk.js:53286:67)
    at GraphRequest.<anonymous> (http://localhost:3000/static/js/vendors~main.chunk.js:53671:99)
    at Generator.throw (<anonymous>)
    at rejected (http://localhost:3000/static/js/vendors~main.chunk.js:59274:32)
```
Using the `ResponseType.RAW` option I get the following response:
```
response: {
  body: null
  bodyUsed: false
  headers: Headers {}
  ok: false
  redirected: false
  status: 0
  statusText: ""
  type: "opaqueredirect"
  url: ...
}
```

## Steps to Reproduce

1. Create a new shareable url for a OneDrive file from user A
2. Set up a msgraph sdk client and authenticate with user B
3. Run the above code passing the url created in step 1. The url needs to be encoded:
```typescript
const encodeSharepointUrl = (url: string) => {
    return (
        "u!" +
        btoa(url).replace("/", "_").replace("+", "-").replace(/=$/, "")
    );
};
```

**Expected behavior:** The request resource is returned or an error with a meaningful message is thrown.

**Actual behavior:** The request fails and a generic error is thrown.

## Additional Context

While trying to perform the same request in Postman I noticed that I get redirected to a similar url on `<Organization>-my.sharepoint.com` but the authentication fails after the redirect.
Interestingly, the problem is resolved after I visit the Sharepoint url once in the browser with user B. I found [this issue](https://docs.microsoft.com/en-us/graph/known-issues#files-onedrive) mentioned in the docs but I am not sure if it is related to the problem I am experiencing. 

Could this be a bug with the library or is this a known issue with the graph API? Is there a potential workaround? 

## Usage Information

SDK Version - 3.0.0-Preview.3

-   [x] Browser

> Browser Name - Google Chrome

> Version - 92.0.4515.107
 
[AB#10460](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10460)

**Comment by nikithauc** [comment] 2021-08-05 21:46
@FreshlyBrewedCode Thanks for reaching out! 

I was not able to reproduce this issue. Before digging if this is a permissions issue, can you please check if the `sharingURL` is being encoded properly and the request is being made. The final request URL to the Graph API gets consoled at the time of the request. Is that getting logged before you get the error?

**Comment by FreshlyBrewedCode** [comment] 2021-08-06 08:32
Thank you for taking the time to investigate this issue @nikithauc.

I posted my code for encoding the URL in my initial post. I just reproduced the issue again and I can confirm that
- The final request URL is logged, even during an unsuccessful request
- The request URL does not change between unsuccessful and successful requests.

As far as I can tell nothing changes between unsuccessful and successful requests in my app. The request just starts succeeding after I open the (unencoded) `sharingURL` manually in the browser. To confirm that this behavior is not caused by some sort of caching or authentication-related cookies etc. I also opened the `sharingURL` in an incognito tab of a different browser. Still the same behavior. After I open the `sharingURL` once manually, the request succeeds. 

> Before digging if this is a permissions issue

- I am using `@azure/msal-react`, `@azure/msal-browser` and `AuthCodeMSALBrowserAuthenticationProvider` for authentication. 
- I am using delegated permissions from an app registration in our tenant:
![image](https://user-images.githubusercontent.com/11772241/128476108-bf9dc115-3402-470c-901a-733034443178.png)
- In my app I request the following scopes:
```javascript
const scopes = ["Files.Read", "Files.Read.All"];
```
- Admin consent has been granted for the app.

Just to clarify, I generate the `sharingURL` by navigating to `https://<Organization>-my.sharepoint.com/personal/<User-A>`, selecting "share" on any file, and copying the link:
![image](https://user-images.githubusercontent.com/11772241/128477432-17de5c37-577c-43a5-9cd9-76ec4e4e7ed2.png)

Unless I am running into a weird edge case, I believe this to be a problem with the graph API that can not be fixed by this library. Also, I can easily work around this problem by showing the user a message and asking them to open the original `sharingURL`. However, the main problem is the generic error message. I spend an entire day figuring out my current workaround. But because there is no explicit error code all I can do is assume the problem based on the raw response:
```typescript
client.api("...")
  .responseType(ResponseType.RAW)
  .get()
  .then((response) => {
      // "Assuming" the problem occoured
      if (
          response !== undefined &&
          response.type === "opaqueredirect"
      ) {
         // Ask user to open sharingURL...
      }
      else {
        response.json().then((result: any) => { /* Handle successful request... */ }
      }
}
```

**Comment by nikithauc** [comment] 2021-08-11 03:03
@ificator Can you please help with this issue?

**Comment by ificator** [comment] 2021-08-11 16:07
We'll need to see the response headers for the request that's generating the 302 - specifically the `request-id` and `Date` headers.

And to get ahead of some potential questions:
1. Does this organization exist in multiple geolocations?
2. Is the request that 302s being made against <organization>.sharepoint.com? I believe that's the case based on comments, but I want to confirm

**Comment by FreshlyBrewedCode** [comment] 2021-08-12 07:47
I reproduced the issue again and collected the response headers:
```
HTTP/1.1 302 Found
Date: Thu, 12 Aug 2021 07:13:21 GMT
Cache-Control: no-cache
Transfer-Encoding: chunked
Location: https://<Organization>-my.sharepoint.com/_vti_bin/client.svc/v2.0/shares('<encodedShareUrl>')/driveItem
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Location, Preference-Applied, Content-Range, request-id, client-request-id, ReadWriteConsistencyToken, SdkVersion, WWW-Authenticate
Strict-Transport-Security: max-age=31536000
request-id: a30dbbbd-376f-4238-876d-ec16bc171b81
client-request-id: 678d8725-4446-5c3c-4a43-0213d338263d
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"E","Ring":"5","ScaleUnit":"001","RoleInstance":"AM4PEPF0000C4CA"}}
```
Regarding your questions:

1. No, the organization is only using one geolocation.
2. No, the request is made against the Graph API:
```
https://graph.microsoft.com/v1.0/shares/<encodedShareUrl>/driveItem
```
The request is started by the msgraph-sdk, i.e.:
```typescript
client.api(`/shares/${encodedUrl}/driveItem`).get()
```

**Comment by kevklam** [comment] 2021-08-12 22:08
Regarding the "after visiting the link in a browser, the API call starts to succeed" behavior - I believe this is because you are not redeeming the link in your request. See the prefer header values documented at https://aka.ms/sharesapi.

Separately - the logs indicate that the failing request is (as expected) due to not having access. However, it's very strange that this is resulting in a 302 redirect. This is almost certainly a bug. We are investigating what might be causing this, but hopefully at least providing the link redemption header will help unblock your immediate needs.

**Comment by FreshlyBrewedCode** [comment] 2021-08-13 07:10
Thanks @kevklam, setting the header solved the issue immediately. I must have completely missed that part of the docs because it says "_Optional_ request headers".
Here is my updated code:
```typescript
client
  .api(`/shares/${encodedUrl}/driveItem`)
  .responseType(ResponseType.RAW)
  .header("Prefer", "redeemSharingLink")
  .get()
  .then((response) => {
    //...
  }
```
Consider this issue closed from my side. 

I agree that the 302 response is very strange and caused a lot of confusion, especially in combination with the msgraph-sdk. Let me know if there is anything else I can do to help investigate the behavior.

**Comment by nikithauc** [comment] 2021-08-13 21:06
@kevklam What do you would be the right action to get the API to return the right error message?

**Comment by nikithauc** [comment] 2021-08-13 23:42
Closing this issue and will open a new action item depending on the steps needed to update the API error message.

**Closed by nikithauc** 2021-08-13 23:42 UTC
Labels: bug: service
